import domain from "./data/domain.json";
import pages from "./data/pages.json";
import services from "./data/services.json";

interface Service {
  id: string;
  name: string;
  description?: string;
  featured?: boolean;
}

interface Pages {
  pages?: Record<
    string,
    {
      path?: string;
      purpose?: string;
      sections?: string[];
    }
  >;
}

function App() {
  const serviceData = services as {
    services?: Service[];
  };

  const pageData = pages as Pages;

  const homePage = pageData.pages?.home;

  return (
    <main>
      <header>
        <h1>{String(domain.name ?? "Business Website")}</h1>
        <p>
          {String(
            domain.description ??
              "Website generated by WebsiteOS"
          )}
        </p>
      </header>

      {homePage && (
        <section>
          <h2>Home</h2>
          <p>
            Purpose: {homePage.purpose ?? "Business information"}
          </p>
        </section>
      )}

      <section>
        <h2>Services</h2>

        {serviceData.services?.map((service) => (
          <article key={service.id}>
            <h3>{service.name}</h3>

            {service.description && (
              <p>{service.description}</p>
            )}

            {service.featured && <strong>Featured</strong>}
          </article>
        ))}
      </section>
    </main>
  );
}

export default App;